### ISSUE TITLE
Add Protocol path example in Working with Protocol section

### ISSUE THREAD

**Issue by maureenlholland** [mozilla/bedrock#10647]
ℹ️ Relevant docs:
General bedrock install: https://bedrock.readthedocs.io/en/latest/install.html
Working with bedrock documentation: https://bedrock.readthedocs.io/en/latest/install.html#documentation
rST Markup**: https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

** OR we could split this section out into a new page and then it'd be easier to use markdown (I think right now you'd have to convert everything in [coding.rst ](https://github.com/mozilla/bedrock/blob/master/docs/coding.rst)to .md)

# Description
We want to reorganize the [Working with Protocol ](https://bedrock.readthedocs.io/en/latest/coding.html#working-with-protocol) section to better explain the distinction between Protocol and Protocol Macros and to make it easier to know what HTML/CSS imports are needed to see Protocol styles on a given page.

The following is V1 (version 1) of what will definitely be an iterative process to get this explanation right (please feel free to make your own suggestions if the V1 approach is unclear):

---

## Working with Protocol (H2)

Bedrock uses the [Protocol Design System](link to https://protocol.mozilla.org/)  to quickly produce consistent, stable components. This involves two steps:
1. Adding the [correct markup](link to styles and components heading) or importing the [appropriate macro](link to macros heading) to a page's HTML file
2. Importing the necessary Protocol styles to a page's SCSS file

### Styles and Components (H3)

The base templates in Bedrock have global styles from Protocol that apply to every page. When we need to extend these styles on a page-specific basis, we set up Protocol in a page-specific SCSS file.

For example, on a Firefox product page, we might want to use Firefox logos or wordmarks that do not exist on every page.

To do this, we add Protocol `mzp-` classes to the HTML:
```html
// bedrock/bedrock/firefox/templates/firefox/{specific-page}.html 

<div class="mzp-c-wordmark mzp-t-wordmark-md mzp-t-product-firefox">
  Firefox Browser
</div>
```

Then we need to include those Protocol styles in the page's CSS: 
```scss
/* bedrock/media/css/firefox/{specific-page}.scss */

/* if we need to use protocol images, we need to set the $image-path variable */
$image-path: '/media/protocol/img'; 
/* mozilla is the default theme, so if we want a different one, we need to set the $brand-theme variable */
$brand-theme: 'firefox';

/* the lib import is always essential: it provides access to tokens, functions, mixins, and theming */
@import '~@mozilla-protocol/core/protocol/css/includes/lib';
/* then you add whatever specific protocol styling you need */
@import '~@mozilla-protocol/core/protocol/css/components/logos/wordmark';
@import '~@mozilla-protocol/core/protocol/css/components/logos/wordmark-product-firefox';
```

NOTE: if you create a new .scss file for a page, you will have to include it in that page's CSS bundle by updating [static-bundles.json](link to https://bedrock.readthedocs.io/en/latest/coding.html#asset-bundling) 

### Macros (H3)

The team has created several [Jinja macros](link to https://jinja2docs.readthedocs.io/en/stable/templates.html#macros) out of Protocol components to simplify the usage of components housing larger blocks of code (i.e. Split). The code housing the custom macros can be found in our [protocol macros file](link to https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/macros-protocol.html).
These Jinja macros include parameters that are simple to define and customize based on how the component should look like on a given page.

To use these macros in files, we simply import a macro to the page's HTML code and call it with the desired arguments, instead of manually adding Protocol markup:
```jinja
// bedrock/bedrock/firefox/templates/firefox/{specific-page}.html 

{% from "macros-protocol.html" import split with context %}

{% call split(
    image_url='img/firefox/browsers/hero.jpg',
    include_highres_image=True,
    block_class='mzp-l-split-center-on-sm-md',
    media_class='mzp-l-split-media-overflow',
    media_after=True
) %}
    <h1>{{ ftl('firefox-browsers-get-the-browsers-strong') }}</h1>
    <p>{{ ftl('firefox-browsers-get-the-privacy-you-deserve') }}</p>
{% endcall %}
```

Because Split styles are not global, we still have to import the page-specific Protocol styles in SCSS:
```scss
/* bedrock/media/css/firefox/{specific-page}.scss */

$brand-theme: 'firefox';

@import '~@mozilla-protocol/core/protocol/css/includes/lib';
@import '~@mozilla-protocol/core/protocol/css/components/split';
```

You can find CSS import paths and parameter definitions for the available Protocol macros below.

NOTE: you can use macros without Protocol and you can use Protocol without macros. They are not dependent on each other but they work well together.

#### Split (and rest of existing macros listed bumped to H4 level)
CSS Import: `@import "~@mozilla-protocol/core/protocol/css/components/split";`

- block_id
- base_el
- block_class
- etc..
