### ISSUE TITLE
ESR release notes link leads to 115, not 128

### ISSUE THREAD

**Issue by martinbalfanz** [mozilla/bedrock#16289]
## Description

When clicking the 'Release notes' link on https://www.mozilla.org/en-US/firefox/all/desktop-esr/ it sends me to the release notes of ESR 115 instead of ESR 128.

### Steps to reproduce

- visit https://www.mozilla.org/en-US/firefox/all/desktop-esr/
- click 'Release notes' link

### Expected result

I should see the release notes of the latest ESR (128)

### Actual result

I see the release notes of ESR 115

### Environment

Firefox Nightly 140 on OS X 15.5

**Comment by janbrasna** [comment]
This is interesting, might be due to the fact 115.x was shipped later on that channel than 128.x:

```yaml
  "name": "Firefox-115.23.1esr-build1",
    "shippedAt": "2025-05-17T21:27:32.056369+00:00",
    "submittedAt": "2025-05-17T17:36:28.834908+00:00"
```

```yaml
  "name": "Firefox-128.10.1esr-build1",
    "shippedAt": "2025-05-17T21:14:51.496456+00:00",
    "submittedAt": "2025-05-17T17:51:27.793386+00:00"
```

I'll look into how the "latest" is evaluated. (It's the same for system requirements etc.)
