### ISSUE TITLE
Links within Firefox banner are blue-on-blue text

### ISSUE THREAD

**Issue by davidjb** [mozilla/bedrock#5820]
The current homepage (https://www.mozilla.org/en-US/) displays a blue-on-blue `requirements` link when the detected browser or system doesn't meet the requirements.

![image](https://user-images.githubusercontent.com/1002811/41519885-514f04f8-72ba-11e8-91bc-008d9f5aaebf.png)

In my case, my platform is determined by Bedrock looking at my `navigator.platform` and determining that I'm on an `oldmac`.  This has the effect to triggering the requirements-not-met message which contains the link, which is blue on blue.  If clicked, that link becomes purple-on-blue which is only just more accessible.

CSS like this would fix it:

```css
.download-firefox-primary-cta a,
.download-firefox-primary-cta a:hover,
.download-firefox-primary-cta a:visited {
  color: #fff;
}
```
