### ISSUE TITLE
/firefox/mobile/ minor UI issues

### ISSUE THREAD

**Issue by alexgibson** [mozilla/bedrock#8137]
## Description

Two small UI issues on the /firefox/mobile/ page

1. The nav links are out of alignment:

![image](https://user-images.githubusercontent.com/400117/68754861-75d64f00-05ff-11ea-90f3-921c97617553.png)

It looks like this is caused by an overly broad selector, which is putting extra padding on every `<li>` in the page:

```scss
//* -------------------------------------------------------------------------- */
//  Download buttons

li {
    padding-top: $spacing-sm;
    display: inline-block;
}
```

2. The main heading is in Inter, but should be using Metropolis:

![image](https://user-images.githubusercontent.com/400117/68755033-cf3e7e00-05ff-11ea-91c1-1a9df53b0ab1.png)

I think this is because the headings are using `<p>` tags, instead of being real headings:

```
<div class="mzp-c-hero-desc">
  <p>Get automatic privacy on mobile</p>
  <p>Super fast. Private by default. Blocks 2000+ online trackers.</p>
</div>
```
